
PY=python
PELICAN=pelican
PELICANOPTS=

BASEDIR=`pwd`
INPUTDIR=$BASEDIR/content
OUTPUTDIR=$BASEDIR/output
CONFFILE=$BASEDIR/pelicanconf.py
PUBLISHCONF=$BASEDIR/publishconf.py

$PELICAN $INPUTDIR -o $OUTPUTDIR -s $CONFFILE $PELICANOPTS

